name: ylham_motors_ui
description: UI package for App Components
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  app_ui:
    path: ../app_ui
  flutter_screenutil: ^5.9.0
  # app_ui:
  #   git:
  #     url: ssh://git@git.asmantiz.com:2235/Koch/super_app_ui_kit.git
  #     ref: dev_atageldi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.3
  flutter_gen_runner: ^5.2.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/bottom_nav_icons/
    - assets/icons/profile_icons/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
