name: ylham_motors
description: "Ylham Motors commerce app"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  app_ui:
    path: ./packages/app_ui

  ylham_motors_ui:
    path: ./packages/ylham_motors_ui

  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  data_provider:
    path: ./packages/data_provider
  equatable: ^2.0.5
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.1
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  persistent_storage:
    path: ./packages/storage/persistent_storage
  secure_storage:
    path: ./packages/storage/secure_storage
  shared_preferences: ^2.2.0
  storage:
    path: ./packages/storage/storage
  flutter_screenutil: ^5.9.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  uses-material-design: true