on:
  push:
    tags:
    - "v*"
name: "Build & Release"
jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17.x"
        cache: "gradle"

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.22.1"
        channel: "stable" # or: 'beta', 'dev' or 'master'
        cache: true

    - name: Download Android keystore
      id: android_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: upload-keystore.jks
        encodedString: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Create key.properties
      run: |
        echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

    - name: Get dependencies
      run: flutter pub get

    - name: Generete l10n
      run: flutter gen-l10n

    - name: Start release build
      run: flutter build apk --split-per-abi -t lib/main/main.dart

    - uses: actions/upload-artifact@v3
      with:
        name: "android-artifact"
        path: "build/app/outputs/apk/release/*.apk"

  release:
    name: Release collected artifacts
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        path: artifacts/

    - name: Display structure of downloaded files
      run: ls -R

    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/android-artifact/*.apk"
        tag: ${{ steps.get_version.outputs.VERSION }}
        token: ${{ secrets.TOKEN }}